### PR TITLE
Redirects: Add redirects for Lib.S.D. repos

### PR DESCRIPTION
**Pull request by seb-slowik**

### CODE REVIEW

**Comment by hughbreslin** [comment]
Hey @seb-slowiko a few comments:

- could you remove the click board redirect please, this should only be used for Microchip GitHub URLs
- We're going to be doing a tidy up of the contents of "_redirects" as its a bit messy at this point with everything, could you make a "soft_miv" folder (or something similar) and add your redirects there? I'm not sure if you'll need to add the full path (i.e "_redirects/soft_miv") to the config file or not but it should be pretty easy to see with a quick test :) This way it'll be a bit easier to find soft Mi-V redirects instead of them getting thrown in with PolarFire SoC ones.

**Comment by seb-slowik** [comment]
Hi @hughbreslin ,

The latest commit should include the necessary corrections.

> Hey @seb-slowiko a few comments:
> 
> * could you remove the click board redirect please, this should only be used for Microchip GitHub URLs
> * We're going to be doing a tidy up of the contents of "_redirects" as its a bit messy at this point with everything, could you make a "soft_miv" folder (or something similar) and add your redirects there? I'm not sure if you'll need to add the full path (i.e "_redirects/soft_miv") to the config file or not but it should be pretty easy to see with a quick test :) This way it'll be a bit easier to find soft Mi-V redirects instead of them getting thrown in with PolarFire SoC ones.

**Comment by hughbreslin** [comment]
Hey @seb-slowiko is there anything else that needs to change with this PR or is it ok to be merged? You'll need @nitindeshpande or @kevinscully100 to merge it for you

**Comment by CLappin** [comment]
> Hey @seb-slowiko is there anything else that needs to change with this PR or is it ok to be merged? You'll need @nitindeshpande or @kevinscully100 to merge it for you

Talked with @seb-slowiko and he is happy for this to be merged.

**Pull request merged**
